cabal-version:  3.0
name:           hnix-attrset-hashmap
version:        0.17.0
synopsis:       HashMap implementation for HNix AttrSet signature
description:    Provides a HashMap-backed implementation of the AttrSet signature.
                Offers O(1) average-case lookup and insertion.
category:       System, Data, Nix
license:        BSD-3-Clause
license-file:   ../../License
build-type:     Simple

flag strict
  description: Enable Strict language extension globally
  manual: True
  default: True

library
  default-language: Haskell2010
  default-extensions:
      NoImplicitPrelude
    , OverloadedStrings
    , DeriveGeneric
    , DeriveFunctor
    , DeriveFoldable
    , DeriveTraversable
    , FlexibleContexts
    , FlexibleInstances
    , ScopedTypeVariables
    , TypeApplications
    , LambdaCase
    , BangPatterns
  if flag(strict)
    default-extensions:
      Strict
  exposed-modules:
    Nix.AttrSet.HashMap
  hs-source-dirs:
    src
  build-depends:
      base >= 4.12 && < 5
    , aeson >= 2.0
    , binary >= 0.8
    , deepseq >= 1.4.3
    , hashable >= 1.3.0
    , hnix-types
    , indexed-traversable >= 0.1.1
    , relude >= 1.0.0
    , semialign >= 1.2
    , serialise >= 0.2
    , template-haskell >= 2.12
    , unordered-containers >= 0.2.14
  ghc-options:
    -Wall
